name: pplib_coprocessor
description: Offload PathPlannerLib's pathfinding to a coprocessor
publish_to: 'none'
version: 0.0.0
repository: https://github.com/mjansen4857/pplib_coprocessor

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
